// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC28XJul0N801oTkwAeuAJy5h4g_BeJ94I',
    appId: '1:301990661937:android:eedf208e0532f626a72a10',
    messagingSenderId: '301990661937',
    projectId: 'railsv2-beb3a',
    storageBucket: 'railsv2-beb3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzzEX2745S4FMXnYyaLGDWGUGHXhBYTP0',
    appId: '1:301990661937:ios:f2afabc4b5b8509fa72a10',
    messagingSenderId: '301990661937',
    projectId: 'railsv2-beb3a',
    storageBucket: 'railsv2-beb3a.appspot.com',
    iosClientId: '301990661937-b9sm4pp5osc442vhrbrobu2cjlr400gn.apps.googleusercontent.com',
    iosBundleId: 'com.rail.hq',
  );
}
